[project]
name = "cdp-neurips"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cdt>=0.6.0",
    "dowhy",
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "networkx>=3.7",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyale>=1.2.0",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "scmtools==0.0.4",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "tqdm>=4.70.1",
]

[tool.uv.sources]
dowhy = { git = "https://github.com/py-why/dowhy.git", rev = "9930609212736449eb1c248440228479e4f99bf4" }

[build-system]
requires = ["uv_build>=0.8.0,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "cdp"
